version: 2

models:
  - name: stg_nasdaq_stocks
    description: "Cleaned staging model for NASDAQ stock data"
    columns:
      - name: symbol
        description: "Stock ticker symbol"
        tests:
          - not_null

      - name: company_name
        description: "Company name"
        tests:
          - not_null

      - name: price
        description: "Latest stock price"
        tests:
          - not_null
