USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS SCRAPE_PIPELINE;
USE DATABASE SCRAPE_PIPELINE;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;


CREATE OR REPLACE TABLE SCRAPE_PIPELINE.RAW.NASDAQ_STOCKS_RAW (
    SYMBOL STRING,
    COMPANY_NAME STRING,
    PRICE FLOAT,
    NET_CHANGE FLOAT,
    CHANGE_PERCENT FLOAT,
    MARKET_CAP FLOAT,
    CATEGORY STRING,
    SOURCE_URL STRING,
    SCRAPED_AT TIMESTAMP
);


CREATE OR REPLACE TABLE SCRAPE_PIPELINE.ANALYTICS.NASDAQ_STOCKS_CLEAN AS
SELECT
    ROW_NUMBER() OVER (ORDER BY SYMBOL) AS STOCK_SK,
    SYMBOL,
    COMPANY_NAME,
    PRICE,
    NET_CHANGE,
    CHANGE_PERCENT,
    MARKET_CAP,
    CATEGORY,
    SOURCE_URL,
    SCRAPED_AT,
    CURRENT_TIMESTAMP AS CREATED_AT

FROM SCRAPE_PIPELINE.RAW.NASDAQ_STOCKS_RAW
WHERE SYMBOL IS NOT NULL;

