
SELECT * FROM SCRAPE_PIPELINE.RAW.NASDAQ_STOCKS_RAW;
SELECT * FROM SCRAPE_PIPELINE.ANALYTICS.NASDAQ_STOCKS_CLEAN;

SELECT
  STOCK_SK,
  SYMBOL,
  COMPANY_NAME
FROM SCRAPE_PIPELINE.ANALYTICS.NASDAQ_STOCKS_CLEAN
LIMIT 10;

SELECT COUNT(*) FROM SCRAPE_PIPELINE.RAW.NASDAQ_STOCKS_RAW;
SELECT COUNT(*) FROM SCRAPE_PIPELINE.ANALYTICS.NASDAQ_STOCKS_CLEAN;

select distinct symbol from SCRAPE_PIPELINE.RAW.NASDAQ_STOCKS_RAW;